server {
    listen 80;

    # Serve l'applicazione React (File statici)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Fondamentale per React Router (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Opzionale: Gzip per performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
